SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `um_external_requests`;
DROP TABLE IF EXISTS `um_item_types`;
DROP TABLE IF EXISTS `um_physical_folders`;
DROP TABLE IF EXISTS `um_physical_folder_types`;
DROP TABLE IF EXISTS `um_tags`;
DROP TABLE IF EXISTS `um_tag_items`;
DROP TABLE IF EXISTS `um_terminals`;
DROP TABLE IF EXISTS `um_terminal_buffer`;
DROP TABLE IF EXISTS `um_virtual_items`;
DROP TABLE IF EXISTS `um_film_information`;
DROP TABLE IF EXISTS `um_film_information_providers`;
SET FOREIGN_KEY_CHECKS=1;